services:
  - docker:1.12.1-dind

stages:
  - build
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t docker.ucalgary.ca/rms/glassfish:3.1.2.2 -t docker.ucalgary.ca/rms/glassfish:latest 3.1.2.2/.
    
push:
  stage: deploy
  script:
    - docker push docker.ucalgary.ca/rms/glassfish
